name: 'Terraform CI/CD Pipeline - Destroy'

on: workflow_dispatch

env:
  TF_VERSION: 1.5.0
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Terraform Init
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select default

      - name: Verify State
        run: terraform state list

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
